package producerconsumer;

import java.util.Random;

/*
Spec sheet states:
While the total number of items generated by all producers is less than 1000
do
{
Randomly generate DD, MM, register#, sale amount.
Create a sales record and place it in the shared buffer.
Increment the number of records count (in the shared memory)
Randomly sleep for 5-40 milliseconds
}
 */

public class Producer extends Thread {
    private Buffer sharedBuffer;
    private int storeID;
    private Random rand = new Random();

    public Producer(Buffer sharedBuffer, int storeID) {
        this.sharedBuffer = sharedBuffer;
        this.storeID = storeID;
    }

    @Override
    public void run() {
    	//Generates our random data per spec sheet, attempts to insert it into our buffer, stops at 1000, and sleeps for a random amount of time (5-40ms) after generating
        while (true) {
            int day = 1 + rand.nextInt(30);
            int month = 1 + rand.nextInt(12);
            int reg = 1 + rand.nextInt(6);
            float amount = 0.50f + rand.nextFloat() * (999.99f - 0.50f);

            SalesRecord record = new SalesRecord(day, month, storeID, reg, amount);

            boolean success = sharedBuffer.insert(record);
            
            if (!success) {
                break;
            }

            try {
                Thread.sleep(5 + rand.nextInt(36));
            } catch (InterruptedException e) {
                break;
            }
        }
    }
}